name: Publish website

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build & deploy website
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/Tota11ylost'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate firebaseConfig.js
        run: |
          echo "window.env = {" > ./src/firebaseConfig.js
          echo "  FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'," >> ./src/firebaseConfig.js
          echo "  FIREBASE_MEASUREMENT_ID: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> ./src/firebaseConfig.js
          echo "};" >> ./src/firebaseConfig.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          cname: tota11ylost.orange.com
