name: Publish website

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build & deploy website
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/Tota11ylost'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
